baseURL = "http://66832007dd14.ngrok.io/"
languageCode = "gr-el"
title = "BeerCityGreece"


[taxonomies]
    material = "materials"
    size = "sizes"
    brewery = "breweries"
    beer_type = "beer_types"
    promotion = "promotions"
    collection = "collections"
    product = "products"

