baseURL: 'https://beersdemo.netlify.app'
languageCode: gr-el
title: BeerCityGreece
DefaultContentLanguage: gr
defaultContentLanguageInSubdir: true
taxonomies:
    promotion: promotions
    collection: collections
    product: products
    collection_lv2: collection_lv2s
    blogtag: blogtags
languages:
    gr:
        title: Παντοπωλείο
        languageName: Ελληνικά
        weight: 1
    en:
        title: Deli Shop
        languageName: English
        weight: 2
params:
    slideshow_promotion: "fiveplusone"
    featured_product: "dark-quinoa-organic-chocolate"
# https://phrase.com/blog/posts/i18n-tutorial-how-to-go-multilingual-with-hugo/#Configure_the_Locales

outputFormats:
  netlifycms_debug:
    baseName: config
    isPlainText: true
    mediatype: text/html
    notAlternative: false
  netlifycms_config:
    baseName: config
    isPlainText: true
    mediatype: application/yaml
    notAlternative: false

outputs:
  home:
    - html
  page:
    - html
  taxonomy:
    - html
    - json
  terms:
    - html
    - json
  term:
    - html
    - json



related:
  indices:
  - name: collections
    weight: 10
    includeNewer: true
  threshold: 80
  toLower: false

# Used by PurgeCSS
# build:
#   writeStats: true

ignoreErrors : "error-remote-getjson"
 