baseURL: 'https://beersdemo.netlify.app'
languageCode: gr-el
title: BeerCityGreece
DefaultContentLanguage: gr
defaultContentLanguageInSubdir: true
taxonomies:
    material: materials
    size: sizes
    brewery: breweries
    beer_type: beer_types
    promotion: promotions
    collection: collections
    product: products
languages:
    gr:
        title: Παντοπωλείο
        languageName: Ελληνικά
        weight: 1
    en:
        title: Deli Shop
        languageName: English
        weight: 2
params:
    slideshow_promotion: "fiveplusone"
    header_message: "Same day local delivery — order by noon for delivery between 2 - 10pm"
# https://phrase.com/blog/posts/i18n-tutorial-how-to-go-multilingual-with-hugo/#Configure_the_Locales

outputFormats:
  netlifycms_debug:
    baseName: config
    isPlainText: true
    mediatype: text/html
    notAlternative: false
  netlifycms_config:
    baseName: config
    isPlainText: true
    mediatype: application/yaml
    notAlternative: false

outputs:
  home:
    - html
    - rss
    - json
  page:
    - html
  taxonomy:
    - html
    - json
  term:
    - html
    - json

# Used by PurgeCSS
build:
  writeStats: true


 