backend:
  name: git-gateway
  repo: dimitrisdervas/snipcart-hugo-forestry
  site_url: https://beersdemo.netlify.app
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://api.netlify.com

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
  - name: "product"
    label: "Products"
    folder: "content/variants"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
  - name: "collection"
    label: "Collections"
    folder: "content/collections"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
  - name: "Config"
    label: "config"
    files:
      - label: "Config"
        name: "config"
        file: "config.yml"
        fields:
          - label: Parametres
            name: params
            widget: string